### ISSUE TITLE
Logged out after a few clicks

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#127]
Steps to reproduce:
1. Log in
2. Update Todo management
3. Click on the third result `59f8833` of the OCR Processed queue
4. Click on the first entry (okay)
5. Click on the second entry 

=> 401 - Unauthorized "Not authenticated." :collision: Afterwards, I am somehow logged out and have to first log in before doing anything.

See here:

![2017-11-01_14-54-39](https://user-images.githubusercontent.com/5199995/32278231-5705e91a-bf15-11e7-8242-06fe6be64097.gif)

**Comment by lgalke** [comment]
That happens when one of the other requests fails. The issue could be reproduced due to your great video. In such cases, the network nab reveals more information:

on both `/getInternalSuggestionsByQueryString` and `/getExternalSuggestionsByQueryString` the response is 502/503

params were 
```js
{ query : "Of%20principle%20and%20principal"
   threshold : "0.7"
}
resulting in:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at locdb.bib.uni-mannheim.de Port 443</address>
</body></html>
```

**Comment by lgalke** [comment]
Without changes (deployed version) the issue was resolved after a reload. Could you please also retry?

**Comment by zuphilip** [comment]
Nope, it is still the same for me. I just tested it with another browser.

**Comment by anlausch** [comment]
Could you try again? There was a problem with null resources in the elasticsearch index not producable locally. Please continue testing and comment on this when the problem persists.

**Comment by anlausch** [comment]
I close the issue for now. Feel free to reopen it again if the problem persists.
