### ISSUE TITLE
Cannot upload pdf for journal article

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#134]
I try to upload a pdf for a journal article with a DOI. However, this does not work and I see some message `Send Scans failed`: 

![locdb-journal-upload](https://user-images.githubusercontent.com/5199995/32292481-9e412792-bf40-11e7-9d83-c77c7d9fcee7.jpg)

Moreover, it should not be necessary to enter any page information in this case.

**Comment by lgalke** [comment]
Hey Philip, thanks for reminding me. The back-end API already just introduced separate parameters for DOI and PPN, but it is not reflected in the front-end yet. I am working on it.

**Comment by lgalke** [comment]
There is a new service `/saveScanForElectronicJournal` instead of `/saveScan`.
Is it safe to assume that setting type to `JOURNAL` should invoke this and only this service? Else the file upload would need to ask for another information which can not be guessed by filename or something else. @zuphilip @anlausch @kleinann

**Comment by lgalke** [comment]
Electronic journals should be fully-functional now (add File to Journal, upload with PPN instead of DOI).
Since page numbers were not used in case of electronic journals, they have been removed from the input as well as the validity checks.

As a bonus: whenever the upload for some specific file / journal fails due to invalid identifer, the corresponding list items now turn read.

Please try to upload some file to an electronic journal again.

**Comment by zuphilip** [comment]
It looks better now, but all my attempts lead to a red box such that the upload still fails. Try this PDF [10.1093sf89.3.763.pdf](https://github.com/locdb/locdb-frend/files/1436652/10.1093sf89.3.763.pdf) with DOI `10.1093/sf/89.3.763` or resp. OLC-SSG-PPN `1870214609`.

**Comment by anlausch** [comment]
@lgalke @zuphilip I can provide the service saveScanForElectronicJournal with the _id of the scan. Then it should not fail anymore.

**Comment by anlausch** [comment]
The new serviceconfiguration is now implemented, but not deployed yet. Could you maybe confirm @lgalke?

**Comment by lgalke** [comment]
Hm, that would require a new upload button attached to each electronic Journal todo item. Until now, we had a clear separation between file upload / data ingestion and the remaining linking process. The reason was that these two tasks might even be performed by two different person groups.

**Comment by anlausch** [comment]
In accordance with @lgalke I changed the service such that it accepts now ppn or doi. In my opinion, the _id solution would be optimal because it's more efficient to compute and super save as we can be 100% sure that the _id is unique and not missing. But, I can see that that would need more changes in the frontend and maybe a concept change regarding the distinction between upload and todos.

**Comment by zuphilip** [comment]
This is a friendly bump. 🐻 🐉 

The issue still exist for me as an end-user. I didn't follow your discussion between frontend and backend completely. Whose turn is next?

**Comment by lgalke** [comment]
Will check. Thought it would be resolved, since the back-end now allows both PPN or DOI to upload file for electronic journal.

The intended steps on-the-frontend are now.

1. Browse Files
2. Switch type from `COLLECTION` to `JOURNAL`
3. Assert that PPN / DOI corresponds to a journal article.
4. Upload

**Comment by zuphilip** [comment]
Yes, that is what I am doing (with the example above), but then receive a `400` from the backend and the box switches to red.

**Comment by lgalke** [comment]
Oh sorry, I just realized that after preparing everything, I forgot to edit the critical 2 lines of code. At the moment it is being deployed on dev.

**Comment by zuphilip** [comment]
Okay, now DOI works ✔️ , but PPN does not work :heavy_multiplication_x: .

**Comment by lgalke** [comment]
For me it works also with PPN. I noticed that all electronic Journals are added by DOI and not PPN.

So 

1. I selected an Journal Ariticle : `Social Forces`/`Commentary: The Kids Are (Mostly) Alright: Second-Generation Assimilation: Comments on Haller, Portes and Lynch` 
2. and added as Identifier `PPN`:`dummyppn`.
3. In File Upload I browse for a file and select `JOURNAL` along with `PPN`
4. It works (gets successfully uploaded), **but** it caused the Journal as a whole to move to `OCR_PROCESSED` instead of `EXTERNAL`.

To some extend it makes sense, since we now have a `ocr_processed` scan attached to it. However, in case of the `OCR_PROCESSED` tab, I do not show the CrossRef references any more.

@anlausch what is the condition on which you decide between the two categories. I would be happy to also adopt the same behaviour in the front-end, to determine whether CrossRef references are available, in which case the respective button needs to be shown.

**Comment by zuphilip** [comment]
Interesting: It seems to work for `dummppn` but not for the real PPN `1870214609`.

The ocr_unprocessed section is fine for me, because it needs a OCR run first.

**Comment by lgalke** [comment]
That's something to inspect tomorrow in more detail.

**Comment by lgalke** [comment]
For now I slightly changed the *condition* for displaying the CrossRef-refs butotn from "was requested in the External Tab" to `resource.parts && resource.parts.length`. The button gets displayed iff, on the todo side, any parent or child resource has `parts` attached to it, containing one or more entries.

**Comment by anlausch** [comment]
I think the intended usage was to *only* upload scans for electronic journals, when the external references are not available. Therefore, I assume it is okay, when the todo, switches to NOT_OCR_PROCESSED as it then has to be treated differently by the user.

I will also investigate on the ppn 1870214609.

**Comment by lgalke** [comment]
Ah i see, technically the front-end should now be able to deal with both variants, since the view (prevalence of crossref button) depends not anymore on the 'state', but on the prevalence of 'parts'. Hope this is in-line with the back-end behaviour.

**Comment by zuphilip** [comment]
The PPN still does not work, and actually also not all DOIs work. I just tried another example with an DOI which does not work:
![doi-another-example](https://user-images.githubusercontent.com/5199995/32383520-77047020-c0b8-11e7-96a5-57c3d5df2423.png)

**Comment by lgalke** [comment]
I just noticed a bug that was introduced with adding the `isTextualPdf` field. It was more related to the Add Electronic Resource button, though. It is fixed now. Regarding the problem, @anlausch is checking whether a todo item with the exact DOI / PPN can be found. Did you assert that such ToDo items are already present?

**Comment by lgalke** [comment]
What is the current state @zuphilip ? Are there any updates?

**Comment by zuphilip** [comment]
I will check again later... Ping me, if you don't hear within a reasonable time...

**Comment by LauraErhard** [comment]
I didn't follow the whole discussion, but I just noticed that I can't choose the DOI  within the "Browse Files" section even if I change the resource type to "journal". And if I switch to PPN in the "Add Electronic Resource" section I can't switch back to DOI.
Was this intentional?

**Comment by lgalke** [comment]
Was not intentional, will check.

**Comment by lgalke** [comment]
Fixed by b2a4d26 . Deploying on `dev`. Ping @zuphilip .

**Comment by LauraErhard** [comment]
I still get the bad request error:
![electronicjournal](https://user-images.githubusercontent.com/32642653/32728865-47825aa2-c882-11e7-8fe3-0fff02887ef1.png)

And a POST error: https://locdb.bib.uni-mannheim.de/locdb-dev/saveScanForElectronicJournal
`Error: Path [/saveScanForElectronicJournal] defined in Swagger, but GET operation is not.
    at middleware (/home/anlausch/locdb-dev/source/node_modules/swagger-node-runner/lib/connect_middleware.js:31:21)
    at Layer.handle [as handle_request] (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:317:13)
    at /home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:335:12)
    at next (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:275:10)
    at cors (/home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:188:7)
    at /home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:224:17
    at originCallback (/home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:214:15)
    at /home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:204:7)
    at Layer.handle [as handle_request] (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:317:13)
    at /home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:335:12)`

Should we wait with further testing until #167 is closed?

**Comment by anlausch** [comment]
The Request should be POST @lgalke.
Also, I think it's okay to continue testing. Any objections @lgalke ?

**Comment by LauraErhard** [comment]
Just FYI: I get the bad request error everytime and the POST error just sometimes.

**Comment by anlausch** [comment]
Maybe you have just accidentally clicked on the URL..

For me, saveElectronicJournals works as expected.
![image](https://user-images.githubusercontent.com/20592651/32730595-e4dcb1e4-c887-11e7-9d0a-a634ad96d3d5.png)

@lgalke Is there maybe some confusion about which service to call when? According to Annettes electronic journals workflow description, librarians enter the doi first and retrieve meta data based on this. Only if there are no references from crossref available, they upload a scan  ( @kleinann  does this still hold?). Therefore, the service expects the journal article already to exist in the DB. But, in case of print journals, the usual /saveScan has to be called, which works with the PPN from ZDB and does both, retrieving meta data and saving the scan.

**Comment by lgalke** [comment]
Ah that could be the misunderstanding. Just tried and for me it worked aswell. Still, the assumption is that the Journal is already present (with respect to its either `PPN` or `DOI`). If one wanted to force up-load a (non-web) journal article, he would have to select `COLLECTION`. At some point the two behaviours could be unified, (if no file present -> check crossref, else save the scan). For now there are two services `/saveScan` which is used for `MONOGRAPH` and `COLLECTION` and `/saveElectronicJournal` + `/saveScanForElectronicJournal` which are invoked when the selected resource type is `JOURNAL`.

**Comment by lgalke** [comment]
e.g. a sketch could look like:

`/saveScanUnified`:
1. if there is a PPN -> check SWB, if there is a DOI -> check Crossref
2. if there is a file and meta-data was found somewhere (step 1) add it.
3. if no file is added check CrossRef/the other PPN thing for existing references

**Comment by LauraErhard** [comment]
Ah okay, I didn't know that I had to "Add Electronic Resource" first. 
Now it works for me too. Sorry for the confusion.

**Comment by kleinann** [comment]
I'm not sure if there is'nt still some confusion about which data to get from which source at which step.

We have different data sources for different publication types, and there are two different kinds of ppns (SWB-ppn and OLC-ppn). For now, the relevant cases shoud be:

1) Type Monograph --> input ppn --> check SWB for metadata
2) Type Collection --> input ppn --> check SWB for metadata of the collection itself
                            --> input DOI --> check Crossref for metadata of a chapter
3) Type Journal --> input ppn --> check OLC for metadata of the article
                        --> input DOI --> check Crossref for metadata of the article

In all these cases, the next steps should be:
- Check Crossref for references to the citing resource. (There is no reference data that can be retrieved by ppn.)
- If there are none, enable the upload of a file.

I tried ppn 1992062145 / doi 10.1016/j.ssresearch.2016.08.020 and wasn't able to upload anything while using "Add Electronic Resource".

**Comment by LauraErhard** [comment]
I just checked your example. The PPN didn't work for me either. But the DOI worked fine. Did the green box with your DOI disappear after uploading, but you couldn't find anything in the todo component? Because that happens when I do it. I think if there are no crossref data nor a scan available the metadata is just put in the database but we (=the user) can't see this. I uploaded a scan after that and the metadata with the scans appeared in the "OCR unprocessed" component.

**Comment by anlausch** [comment]
@kleinann In the workflow description excel file, there was written ZDB for meta data as a whole for journals. What's the status on this?

**Comment by kleinann** [comment]
@anlausch Yes - you're right. But in my mind, fetching and storing the metadata for the whole journal is a one time thing, because we have a fixed list of journals that we want to process, and we'll only have to get the metadata for that once at the beginning (or even only store the URI for the resource from the ZDB-LOD Service?). So this can be done manually. Ideally, all articles belonging to that journal would inherit the journal information (at least: the zdb-id) from the journal that they belong to.

**Comment by kleinann** [comment]
@LauraErhard That was the behaviour of the DOI, indeed. A bit confusing when the entry just disappears, isn't it? Could we show the metadata and make it possible to upload a file for that resource afterwards?
