### ISSUE TITLE
Cannot "add entry" to reference list

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#442]
I just tried to add another entry to a reference list and I see this after clicking `add entry`:
![addentry](https://user-images.githubusercontent.com/32642653/49882256-8222bc80-fe30-11e8-8d7d-ab33aef0617e.png)
This can't be right. I would expect that I only get the second form.

I don't know if the 400 error that follows my `submit` is a consequential error of the first problem but here is the error:
```
Error creating entry 
Object { headers: {…}, status: 400, statusText: "Bad Request", url: "https://locdb.bib.uni-mannheim.de/locdb/bibliographicEntries?bibliographicResourceId=5a2175daa2bb9026f446e2bb", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://locdb.bib.uni-mannheim.de/locdb/bibliographicEntries?bibliographicResourceId=5a2175daa2bb9026f446e2bb: 400 Bad Request", error: {…} }
```

**Comment by chah3d** [comment]
The double form is fixed for the next version.
The creation of a new entry on the post bibliographicEntry interface still raises a validation error. 
![selection_029](https://user-images.githubusercontent.com/32481062/50486550-d5813700-09fa-11e9-8c7b-0fe0091a1ba5.png)
(Resource id/Query string: 5bc6f1700e466f16dff1c0b7)
It seems like the validation of the Entry ID (according to the pattern) fails because it does not exist. Are there other attributes that are mandatory for the creation of a new entry, so we can catch faulty entries before transmission? (At the moment even an empty entry can be created which may be of limited use)

**Comment by LauraErhard** [comment]
Should I see any changes yet in any of our systems? The only thing I see is in the dev version I still get the double form and strange additional text at the beginning of the page:
![unbenannt](https://user-images.githubusercontent.com/32642653/50956866-17ab7d80-14bd-11e9-952f-5505634a9da6.png)

**Comment by lgalke** [comment]
@chah3d does it make sense to deploy a new version on dev | on prod? @abdelqader-mohammad I could do it you want me to.

**Comment by lgalke** [comment]
I pushed a fix and deployed it on dev and prod. @abdelqader-mohammad the debug information was only shown at dev endpoint. I also now disabled it, there.

**Comment by lgalke** [comment]
2416ed4d2fdbba0443fa44bc405fcddcda68c6b0

**Comment by LauraErhard** [comment]
Thanks for your quick work, everything looks good now.

But I can't `submit` the new entry, I always get the following error:

Error creating entry 
Object { headers: {…}, status: 400, statusText: "Bad Request", url: "https://locdb.bib.uni-mannheim.de/locdb/bibliographicEntries?bibliographicResourceId=5a548f95fcaa4703f0194ec1", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://locdb.bib.uni-mannheim.de/locdb/bibliographicEntries?bibliographicResourceId=5a548f95fcaa4703f0194ec1: 400 Bad Request", error: {…} }

**Comment by lgalke** [comment]
We call the [entry.create](https://locdb.bib.uni-mannheim.de/locdb-dev/docs/#/BibliographicEntry/create) service from the backend. Inspecting the error message, it is caused by a spurious validation check that enforces the 'references' field to be filled with some id.


See the screenshot:
![image](https://user-images.githubusercontent.com/3439126/50966878-ac6ea500-14d6-11e9-8d24-5298e5d28cbf.png)


Of course that should not happen at that point, @anlausch needs to tackle this.
